Add dependabot for github actions
SkynetLabs/.github pull request #12
Opened 2022-04-21 20:40 UTC by MSevey

# PULL REQUEST

## Overview
Add Dependabot for keeping github actions up to date.

2022-04-22 08:05 UTC, kwypchlo requested changes

2022-04-22 08:05 UTC, kwypchlo commented on .github/dependabot.yml
> +      interval: "weekly"
let's do monthly, it was proven in several different repos that weekly is a bit too often and feels spammy

```suggestion
      interval: "monthly"
```

2022-04-26 10:59 UTC, ro-tex approved these changes

2022-04-26 23:11 UTC, m-cat approved these changes

2022-04-27 08:48 UTC, merged